spring:
    application:
        name : ConfigServer
        
server:
    port : 8089

#This expose everything. in production this shouldnt be written.
management.endpoints.web.exposure.include : "*" 

spring.cloud.config.uri : http://localhost:8888

#This will pull the configuration file from spring cloud with the same name of this application name
spring.application.name : spring-boot-config

